### ISSUE TITLE
NASA RSS feed provides wrong year in early January, making the Next Event from the sensor incorrect

### ISSUE THREAD

**Issue by RACMan2527** [Staples1010/Add-the-next-Spot-the-Station-event-to-Home-Assistant-sensor#1]
Started using the python script in 2024.  Works great.  Thank you.
Starting on Jan 1, discovered that the sensor would return the incorrect Next Event.
Found the reason to be an error on the NASA RSS feed where the past events (in Dec 2023) were being shared as Dec 2024.  The python script would consume the Dec 2024 as a future date and report these when in reality there were January events that should have been reported.

Take note of the RSS feed for the last 2 days of 2023 and the first 2 days of 2024:
<item>
<title>2024-12-30 NG-19 Sighting</title>
<pubDate>02 Jan 2024 22:54:13 GMT</pubDate>
<description> Date: Saturday Dec 30, **2024** <br/> Time: 5:37 AM <br/> Duration: 1 minute <br/> Maximum Elevation: 11° <br/> Approach: 11° above NNE <br/> Departure: 10° above NNE <br/> </description>
<guid>https://spotthestation.nasa.gov/sightings/view.cfm?country=United_States&region=Delaware&city=Lewes&ss=2AA1359E-7FC7-4F3E-967F3ACFAA308DCF</guid>
</item>
<item>
<title>2024-12-31 NG-19 Sighting</title>
<pubDate>02 Jan 2024 22:54:13 GMT</pubDate>
<description> Date: Sunday Dec 31, **2024** <br/> Time: 6:18 AM <br/> Duration: 5 minutes <br/> Maximum Elevation: 23° <br/> Approach: 11° above NNW <br/> Departure: 10° above E <br/> </description>
<guid>https://spotthestation.nasa.gov/sightings/view.cfm?country=United_States&region=Delaware&city=Lewes&ss=1CA6E152-0EAC-4D27-87E3AAA44B061A85</guid>
</item>
<item>
<title>2024-01-01 NG-19 Sighting</title>
<pubDate>02 Jan 2024 22:54:13 GMT</pubDate>
<description> Date: Monday Jan 1, **2024** <br/> Time: 5:26 AM <br/> Duration: 2 minutes <br/> Maximum Elevation: 16° <br/> Approach: 16° above NNE <br/> Departure: 10° above ENE <br/> </description>
<guid>https://spotthestation.nasa.gov/sightings/view.cfm?country=United_States&region=Delaware&city=Lewes&ss=5B0CD85D-6E2B-4302-B585B8820A06BC0E</guid>
</item>
<item>
<title>2024-01-02 ISS Sighting</title>
<pubDate>02 Jan 2024 22:54:13 GMT</pubDate>
<description> Date: Tuesday Jan 2, **2024** <br/> Time: 5:34 AM <br/> Duration: 3 minutes <br/> Maximum Elevation: 24° <br/> Approach: 23° above N <br/> Departure: 10° above E <br/> </description>
<guid>https://spotthestation.nasa.gov/sightings/view.cfm?country=United_States&region=Delaware&city=Lewes&ss=D49E71ED-22C7-403A-862D88B2E7DE3D6E</guid>
</item>

To correct this, I added the following code after the the following at line 36:
        # Exclude past events
        if event_start < current_time:
            continue

        **# Check if STS provided the wrong year in early Jan for Dec dates
        if event_start.month == 12 and current_time.month == 1:
            continue**

**Comment by PyrokineticDarkElf** [comment]
@RACMan2527 Good spot! I 100% would have missed this. I've updated the script :D
